### ISSUE TITLE
Rappelling notification mistake

### ISSUE THREAD

**Issue by NICKOLAS78GR** [zachun/impulse-issues#1]
**Describe the bug**
When using the /rappel command instead if "You have **started** rappelling." it says "You have **stopped** rappeling.", also rappelling is with only 1 L instead of 2 which is the correct way to spell it, same goes for the "You have ended rappeling." notification.

**Screenshots**

**impulse version (press F1 in the bottom right):**
1.74

**Additional notes**
This could honestly be reported in just a small chat message but it's 10AM for me and the Discord/Server is dead

**Comment by zachun** [comment]
Fixed!
