### ISSUE TITLE
Airwatch adds wrong BOL charge when scanning rebels

### ISSUE THREAD

**Issue by NICKOLAS78GR** [zachun/impulse-issues#2]
**Describe the bug**
Instead of the Disassociation but when scanning a rebel they get the 10-103M charge

**Expected behaviour**
Scanned rebels should get the BOL for the Disassociation from the Civic Populous charge instead of the 10-103M

**impulse version (press F1 in the bottom right):**
1.74

**Comment by zachun** [comment]
Fixed!
