### ISSUE TITLE
Ranger OTA terminal minor bug

### ISSUE THREAD

**Issue by NICKOLAS78GR** [zachun/impulse-issues#5]
**Describe the bug**
Terminal shows Ranger EOW- as part of the Echo division.

**To reproduce**
Steps to reproduce the behaviour:
1. Go Ranger OWS or EOW
2. Check the front page of a terminal
3. See the bug

**Expected behaviour**
Local division should state "RANGER"

**Screenshots**
![image](https://github.com/zachun/impulse-issues/assets/81629850/28aa6025-209e-4615-8d6c-5cac324eb19d)

**impulse version (press F1 in the bottom right):**
1.74

**Additional context**
 it might have been caused by the recent model change in the division which also may have caused the bug that prevents you from switching to another job as OTA, or maybe that last part is an intended feature for when being inside the nexus

**Comment by zachun** [comment]
Fixed
